### ISSUE TITLE
Dawn and dusk in zmanim

### ISSUE THREAD

**Issue by MaxBGreenberg** [hebcal/hebcal-go#10]
Currently, the list of zmanim includes dawn and dusk (6 degrees of solar depression). however, i cannot find any halakhic significance to these zmanim and was wondering why they belong in the zmanim list. in my fork, i've removed them from the list. I've implemented a bein hashmashos zman in place of dusk which occurs 13.5 minutes before a solar depression of 7.083 degrees. hebcal currently uses dusk (6 degrees of solar depression) as the zman for hadlakas neir chanukka. I am curious as to the basis of this decision. the shitos i've seen for zman hadlaka neir chanukka are sunset, tzeis hakhochavim, and bein hashmashos (the latter 2 are based on the lashon of shulkhan arukh of zman being im sof shkias hachama). For this reason, in my fork, i've implemented zman hadlakas neir chanukka as being at bein hashmashos. if there is no reason to keep the 6 degree dawn and dusk, I will submit that change as a PR

**Comment by mjradwin** [comment]
Thanks you! Your suggestion to replace civil dusk with bein hashmashos for weekday Chanukah candle-lighting times is an excellent one. At the time the feature was implemented many years ago, it was proposed by a user with less halachic knowledge. I can't find the exact source for why civil dusk was used, but it makes so much more sense to replace with something grounded in the halacha.

I don't know if there are applications depending on the presence of 6-degree dawn and dusk, so there is a remote chance that removing them could cause breakage. However, the hebcal-go library is versioned at 0.x which doesn't promise 100% stability, so again, it seems fine to remove these.

**Comment by MaxBGreenberg** [comment]
I would also add it to the zmanim list with -Z. some communities (i think mainly ones of chassidish extraction and including my own) daven maariv after this zman

**Comment by MaxBGreenberg** [comment]
@mjradwin  Ok so it seems that the time for chanukka candle lighting was changed to be at Tzeis3medium stars already but the documentation was never updated.

**Comment by mjradwin** [comment]
Fixed in v0.9.28
